FROM bitnami/java:21.0.3-12
VOLUME /tmp
COPY target/PhotoAppApiAccountManagement-0.0.1-SNAPSHOT.jar account-microservice.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/account-microservice.jar"]